### ISSUE TITLE
Github actions workflow Error

### ISSUE THREAD

**Issue by radhikatoravi15** [SN-18/SE-Homework-2b#24]

**Comment by pncnmnp** [comment]
I will look into this today. Lets try and integrate pytest with Github Actions.

**Comment by SN-18** [comment]
I am thinking of adding a workflow badge to README.md, should I go ahead and do that or would you like to resolve this first?

**Comment by pncnmnp** [comment]
@radhikatoravi15 I have proposed #37 and #38 which adds a Github actions workflow. Can you please test and confirm.

**Comment by pncnmnp** [comment]
The proposals #37 and #38 have been merged.
