### ISSUE TITLE
Build test causing check failures in pull request

### ISSUE THREAD

**Issue by SN-18** [SN-18/SE-Homework-2b#29]
The build test rule is causing "check failure" for pull requests, even ones that involve documentation.

I believe this particular line is the root of the problem:
https://github.com/SN-18/SE-Homework-2b/blob/5ce4167c8b4fa38f8fff64c3945e86176512947e/.github/workflows/python-app.yml#L35

**Comment by rdeodha** [comment]
Build seems to be passing now, closing issue.
